name: Build MX4300 NSS

on: workflow_dispatch

jobs:
    build:
        name: Build MX4300 NSS firmware images
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Install packages
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                      build-essential \
                      clang \
                      flex \
                      bison \
                      g++ \
                      gawk \
                      gcc-multilib \
                      g++-multilib \
                      gettext \
                      git \
                      libncurses-dev \
                      libssl-dev \
                      python3-distutils \
                      rsync \
                      unzip \
                      zlib1g-dev \
                      file \
                      wget && \
                  sudo apt-get clean

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update feeds
              # run:  make package/symlinks
              run: cp feeds.conf.default feeds.conf 
               && echo "src-git custom_packages https://github.com/RainGater/OpenWRT-Packages" >> feeds.conf
               && scripts/feeds update -a 
               && scripts/feeds install -a

            - name: Generate MX4300 NSS Config
              # run: sh mx4300_nss_config.sh 
              run: cp nss-setup/config-nss.seed .config 
               && echo "CONFIG_ATH11K_THERMAL=y" >> .config 
               && echo "CONFIG_KMOD_ALL=y" >> .config 
               && echo "CONFIG_PACKAGE_collectd-mod-thermal=y" >> .config 
               && echo "CONFIG_PACKAGE_luci-app-temp-status=y" >> .config 
               && echo "CONFIG_FEED_custom_packages=n" >> .config
               && echo "CONFIG_TARGET_qualcommax=y" >> .config
               && echo "CONFIG_TARGET_qualcommax_ipq807x=y" >> .config
               && echo "CONFIG_TARGET_qualcommax_ipq807x_DEVICE_linksys_mx4300=y" >> .config

            - name: Build Config
              run: make defconfig V=s -j$(nproc)

            - name: Build Images
              run: make V=s -j$(nproc)

            - name: Get SHORT SHA 
              run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                tag: mx4300-nss-${{ env.SHORT_SHA }}
                artifacts: bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x*.bin,bin/targets/qualcommax/ipq807x/openwrt-qualcommax-ipq807x-linksys_mx4300.manifest,.config
